# -*- coding: utf-8 -*-
"""PrimeSilverlayertransformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SrGU9og389Io_fO71RiGb_OpzVgdyoiO
"""

spark.conf.set("fs.azure.account.auth.type.adlsprimework.dfs.core.windows.net", "OAuth")
spark.conf.set("fs.azure.account.oauth.provider.type.adlsprimework.dfs.core.windows.net", "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider")
spark.conf.set("fs.azure.account.oauth2.client.id.adlsprimework.dfs.core.windows.net", "7cc6867a-2661-46e8-b4de-eaf76462a2bb")
spark.conf.set("fs.azure.account.oauth2.client.secret.adlsprimework.dfs.core.windows.net", "a1m8Q~yfElSxhXuQxnDQU73LZB4o~gaZwTSbTbH-")
spark.conf.set("fs.azure.account.oauth2.client.endpoint.adlsprimework.dfs.core.windows.net", "https://login.microsoftonline.com/f045ba8f-f191-46d0-9b94-ddef417b68ad/oauth2/v2.0/token")

dbutils.fs.ls('abfss://bronze@adlsprimework.dfs.core.windows.net/')

from pyspark.sql.functions import *
from pyspark.sql.types import*

"""DATA UNDESTANDING"""

df_silver = spark.read.format("csv")\
    .option("header", "true")\
    .option("inferSchema", "true")\
    .load("abfss://bronze@adlsprimework.dfs.core.windows.net/amazon_prime_titles.csv")
df_silver.display()

df_silver.printSchema()

"""DATA CLEANING"""

df_silver = df_silver.na.fill({'rating':'Unrated','country':'Unknown'})
df_silver.display()

df_silver = df_silver.dropDuplicates()
df_silver.display()

df_silver = df_silver.na.fill({'rating':'Unrated','country':'Unknown','date_added':'01/01/2025', 'release_year':'2020', 'duration':'Unkown',
                               'listed_in':'Unknown', 'description':'Unknown', 'director':'Unknown', 'cast':'Unknown'})
df_silver.display()

df_silver = df_silver.dropna('any')
df_silver.display()

df_silver = df_silver.withColumnRenamed('title','content_title')
df_silver.display()

df_silver = df_silver.withColumn('is_country', when(col('country') == 'Unknown', 0).otherwise(1))
df_silver.display()

df_silver.write.format("parquet")\
.mode("append")\
    .save("abfss://silver@adlsprimework.dfs.core.windows.net/amazon_prime_titles_silver.csv")